#!/usr/bin/env python3
"""Convert a markdown meeting notes file to a styled HTML page."""
import sys
import re
from pathlib import Path
import markdown

TEMPLATE = """<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  :root {{
    --bg: #0f1117; --surface: #1a1d27; --surface2: #22263a;
    --border: #2e3349; --text: #e2e4ef; --muted: #7880a0;
    --green: #22c55e; --yellow: #f59e0b; --blue: #3b82f6;
    --purple: #a855f7; --red: #ef4444;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: var(--bg); color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans KR', sans-serif;
    font-size: 15px; line-height: 1.75;
    padding: 48px 24px; max-width: 860px; margin: 0 auto;
  }}
  h1 {{ font-size: 26px; font-weight: 700; color: #fff; margin-bottom: 28px;
        padding-bottom: 16px; border-bottom: 1px solid var(--border); }}
  h2 {{ font-size: 18px; font-weight: 600; color: #fff; margin: 40px 0 14px;
        padding-bottom: 8px; border-bottom: 1px solid var(--border); }}
  h3 {{ font-size: 15px; font-weight: 600; color: #d4d8f0; margin: 24px 0 10px; }}
  h4 {{ font-size: 14px; font-weight: 600; color: var(--muted); margin: 18px 0 8px; text-transform: uppercase; letter-spacing: 0.4px; }}
  p {{ margin-bottom: 12px; }}
  a {{ color: var(--blue); text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  strong {{ color: #fff; font-weight: 600; }}
  ul, ol {{ padding-left: 22px; margin-bottom: 12px; }}
  li {{ margin-bottom: 5px; }}
  li input[type="checkbox"] {{ margin-right: 7px; accent-color: var(--blue); }}
  table {{
    width: 100%; border-collapse: collapse;
    margin: 16px 0; font-size: 14px;
  }}
  th {{
    background: var(--surface2); color: #fff;
    padding: 9px 14px; text-align: left;
    border: 1px solid var(--border); font-weight: 600;
  }}
  td {{
    padding: 8px 14px; border: 1px solid var(--border);
    background: var(--surface); vertical-align: top;
  }}
  tr:hover td {{ background: var(--surface2); }}
  th:first-child, td:first-child {{ white-space: nowrap; width: 1%; }}
  pre {{
    background: var(--surface2); border: 1px solid var(--border);
    border-radius: 8px; padding: 16px; overflow-x: auto;
    margin: 14px 0; font-size: 13px; line-height: 1.6;
  }}
  code {{
    background: var(--surface2); border-radius: 4px;
    padding: 2px 6px; font-size: 13px; font-family: 'SF Mono', 'Fira Code', monospace;
  }}
  pre code {{ background: none; padding: 0; }}
  blockquote {{
    border-left: 3px solid var(--border); margin: 16px 0;
    padding: 10px 18px; color: var(--muted);
    background: var(--surface); border-radius: 0 6px 6px 0;
  }}
  hr {{ border: none; border-top: 1px solid var(--border); margin: 32px 0; }}
  .footer {{
    margin-top: 48px; padding-top: 16px;
    border-top: 1px solid var(--border);
    font-size: 12px; color: var(--muted);
    display: flex; justify-content: space-between;
  }}
</style>
</head>
<body>
{body}
<div class="footer">
  <span>{source_file}</span>
  <span>Generated by Audio2Text</span>
</div>
</body>
</html>"""


def convert(md_path: Path) -> Path:
    text = md_path.read_text(encoding="utf-8")

    # GitHub-style task list: - [ ] and - [x]
    text = re.sub(r"^(\s*)-\s\[ \]", r"\1- <input type='checkbox' disabled>", text, flags=re.MULTILINE)
    text = re.sub(r"^(\s*)-\s\[x\]", r"\1- <input type='checkbox' checked disabled>", text, flags=re.MULTILINE)

    html_body = markdown.markdown(
        text,
        extensions=["extra", "toc", "sane_lists"],
    )

    # 테이블 셀 안의 ②③… 앞에 줄바꿈 삽입 (①은 첫 항목이므로 유지)
    html_body = re.sub(r"([②③④⑤⑥⑦⑧⑨⑩])", r"<br>\1", html_body)

    # Extract title from first h1
    title_match = re.search(r"<h1[^>]*>(.*?)</h1>", html_body)
    title = re.sub(r"<[^>]+>", "", title_match.group(1)) if title_match else md_path.stem

    html = TEMPLATE.format(
        title=title,
        body=html_body,
        source_file=md_path.name,
    )

    out_path = md_path.with_suffix(".html")
    out_path.write_text(html, encoding="utf-8")
    print(f"✅ {out_path}")
    return out_path


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/md_to_html.py <markdown-file>")
        sys.exit(1)
    convert(Path(sys.argv[1]))
